# Generated by Django 4.1.3 on 2022-12-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realestate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('space', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
