# Generated by Django 4.1.3 on 2022-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_car_type_realestate_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=4)),
                ('description', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('Images', models.ImageField(upload_to='photos/%y/%m/%d')),
            ],
        ),
    ]
