# Generated by Django 4.1.3 on 2022-12-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_car_user_jet_user_realestate_user_yacht_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jet',
            old_name='description',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='description',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='yacht',
            old_name='description',
            new_name='features',
        ),
    ]
