# Generated by Django 4.1.3 on 2022-12-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_car_user_alter_jet_user_alter_realestate_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Images',
        ),
        migrations.RemoveField(
            model_name='jet',
            name='Images',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='Images',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='Images',
        ),
        migrations.AddField(
            model_name='car',
            name='Image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='jet',
            name='Image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='realestate',
            name='Image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='yacht',
            name='Image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Multimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.FileField(upload_to='photos/%y/%m/%d')),
                ('cars', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
                ('jets', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.jet')),
                ('realestates', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.realestate')),
                ('yachts', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.yacht')),
            ],
        ),
    ]
