# Generated by Django 4.1.3 on 2022-12-05 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_car_images_remove_jet_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimg',
            name='cars',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
        ),
        migrations.AlterField(
            model_name='multimg',
            name='jets',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.jet'),
        ),
        migrations.AlterField(
            model_name='multimg',
            name='realestates',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.realestate'),
        ),
        migrations.AlterField(
            model_name='multimg',
            name='yachts',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.yacht'),
        ),
    ]
